server {
	listen 80;
	server_name ${HOST};
	location / {
		return 404;
	}
}

server {
	listen 80;
	server_name charterauthority.${HOST};
	location / {
		proxy_pass http://charter-authority;
	}
}

server {
	listen 80;
	server_name tokenexchange.${HOST};
	location / {
		proxy_pass http://token-exchange;
	}
}

server {
	listen 80;
	server_name livery.${HOST};
	location / {
		proxy_pass http://livery;
	}
}

server {
	listen 80;
	server_name wagonrepair.${HOST};
	location / {
		proxy_pass http://wagon-repair;
	}
}

server {
	listen 80;
	server_name generalstore.${HOST};
	location / {
		proxy_pass http://general-store;
	}
}

server {
	listen 80;
	server_name banditnegotiation.${HOST};
	location / {
		proxy_pass http://bandit-negotiation;
	}
}

server {
	listen 80;
	server_name inn.${HOST};
	location / {
		proxy_pass http://inn;
	}
}

server {
	listen 80;
	server_name bank.${HOST};
	location / {
		proxy_pass http://bank;
	}
}

server {
	listen 80;
	server_name trailhead.${HOST};
	location / {
		proxy_pass http://trailhead;
	}
}
